### ISSUE TITLE
Change link 

### ISSUE THREAD

**Issue by leverkune** [tsvetta/atlantic_challenge_rus#1]
Change link in Тренировки => Записаться - нужна ссылка в ВК, не на гугл форму

**Comment by Nitive** [comment]
Наоборот же специально сделали здесь ссылку на форму для тех, кто уже ходит на тренировки?

**Comment by leverkune** [comment]
Ну тут про тренировки, я так поняла, чтобы люди записаться моглт на них
А ссылка для команды отдельно внизу. Имеется в виду вот это: 

![image](https://user-images.githubusercontent.com/51372310/59368290-934c7780-8d46-11e9-88cc-57f4b210a36c.png)

**Comment by Nitive** [comment]
Исправлено в https://github.com/tsvetta/atlantic_challenge_rus/commit/7fe6070c71e3e454b009ff690520d5bf397d4e05
