### ISSUE TITLE
Change text

### ISSUE THREAD

**Issue by leverkune** [tsvetta/atlantic_challenge_rus#2]
Now: Россия впервые принимает международную молодежную регату парусно-гребных шлюпок Atlantic Challenge, стань участником этого уникального события.

Should be: Россия впервые принимает международную молодежную регату парусно-гребных шлюпок Atlantic Challenge. Стань участником этого уникального события!

**Comment by Nitive** [comment]
Исправлено в https://github.com/tsvetta/atlantic_challenge_rus/commit/b20ff9e43f9b6656c1efbdceee280da1947bb395
