### ISSUE TITLE
Footer!!!

### ISSUE THREAD

**Issue by leverkune** [tsvetta/atlantic_challenge_rus#4]
Он ЛеднЁв, а не ЛеНДёв

**Comment by Nitive** [comment]
Исправлено в https://github.com/tsvetta/atlantic_challenge_rus/commit/f688456aed1043374fda8922a3a92b39664b95ab

**Comment by leverkune** [comment]
У меня по-прежнему так: 
![image](https://user-images.githubusercontent.com/51372310/59368445-ed4d3d00-8d46-11e9-8884-a5531aafd2ed.png)

Или это еще Таня на странице должна поправить?

**Comment by Nitive** [comment]
@leverkune у меня вроде всё ок, проверь ещё раз, плиз

**Comment by leverkune** [comment]
Все круто! Исправилось.
