### ISSUE TITLE
Текст с подпиской по e-mail

### ISSUE THREAD

**Issue by leverkune** [tsvetta/atlantic_challenge_rus#6]
Почему-то мне помнится, что был другой вариант текста. 
![image](https://user-images.githubusercontent.com/51372310/59380881-c6046900-8d62-11e9-96fb-16cc7175f3a8.png)

Типа, пишем примерно раз в месяц. Про спам вроде решили убрать.

**Comment by Nitive** [comment]
Внизу поменяли. В блоке, который ты скинула, тоже можно поменять

![image](https://user-images.githubusercontent.com/6770225/59387343-97da5580-8d71-11e9-8c12-3d7c04b2a3f5.png)

**Comment by leverkune** [comment]
Оставим как есть! =)
